# Generated by Django 6.0.3 on 2026-03-24 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflix', '0010_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='appflix.review')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário de review',
                'verbose_name_plural': 'Comentários de reviews',
                'ordering': ['data_criacao'],
            },
        ),
    ]
