# Generated by Django 4.2.16 on 2026-03-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflix', '0011_comentarioreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AddField(
            model_name='comentarioreview',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
